name: Multi Job Workflow

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: echo "This is Job 1 running" > data.txt
      - name: upload file as artifact
        run: actions/upload-artifact@v4

  job2:
    runs-on: job1
    steps:
      - name: download artifactfile
        uses: actions/download-artifact@v4
        with:
          name: datafile
      
      - name: show file content
        run: cat data.txt
